---
kind: pipeline
name: default
type: kubernetes
clone:
  disable: true
steps:
- name: test
  pull: default
  image: node:14
  commands:
    - echo $NPM_RC | base64 -d > .npmrc
    - npm ci
    - npm run build-test
    - npm run lint
    - npm test
  environment:
    NPM_TOKEN:
      from_secret: npm_token
    NPM_RC:
      from_secret: npm_rc
