---
kind: pipeline
name: default
type: kubernetes
clone:
  disable: true
steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 1

- name: build_image
  pull: default
  image: plugins/docker
  settings:
    repo: seetransparent/apps
    tags: csv-format-converter-${DRONE_COMMIT_SHA}
    network_mode: host
    build_args_from_env:
    - BOT_SSH_KEY
    - NPM_RC
    - NPM_TOKEN
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    BOT_SSH_KEY:
      from_secret: bot_ssh_key
    NPM_RC:
      from_secret: npm_rc
    NPM_TOKEN:
      from_secret: npm_token

- name: lint
  pull: default
  image: seetransparent/apps:csv-format-converter-${DRONE_COMMIT_SHA}
  commands:
  - cd /app
  - npm run lint
  environment:
    NODE_ENV:
      from_secret: node_env
    NPM_TOKEN:
      from_secret: npm_token

- name: unit_test
  pull: default
  image: seetransparent/apps:csv-format-converter-${DRONE_COMMIT_SHA}
  commands:
  - cd /app
  - npm run build-test
  - npm run test
  environment:
    NODE_ENV:
      from_secret: node_env
    NPM_TOKEN:
      from_secret: npm_token
