---
kind: pipeline
name: default
type: kubernetes
platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: node:14
  commands:
    - echo $NPM_RC | base64 -d > .npmrc
    - npm install
    - npm run build-test
    - npm run lint
    - npm test
  environment:
    NPM_TOKEN:
      from_secret: npm_token
    NPM_RC:
      from_secret: npm_rc
